version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: users_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-users_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-users_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nebula-network

  postgres_notifications:
    image: postgres:16-alpine
    container_name: notifications_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: notifications_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - pgdata_notifications:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d notifications_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nebula-network

  redis:
    image: redis:7-alpine
    container_name: nebula_redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 256mb
      --maxmemory-policy noeviction
      --requirepass ${REDIS_PASSWORD:-default_password}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-default_password}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - nebula-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nebula_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - nebula-network

  users:
      build:
        context: .
        dockerfile: services/users/Dockerfile
      container_name: app_users
      environment:
        # DB (users)
        USERS_DB_HOST: postgres
        USERS_DB_PORT: 5432
        USERS_DB_USER: ${DB_USER:-postgres}
        USERS_DB_PASSWORD: ${DB_PASSWORD:-postgres}
        USERS_DB_NAME: ${DB_NAME:-users_db}
        # RMQ
        RMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/${RABBITMQ_VHOST:-/}
        RMQ_EXCHANGE: app.events
        RMQ_PREFETCH: 20
        # Redis
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DB: 0
        REDIS_PASSWORD: ${REDIS_PASSWORD:-default_password}
        # Notifications
        WEBHOOK_URL: ${WEBHOOK_URL:-http://localhost:3000/webhook}
        PUSH_DELAY_HOURS: 24
        # Common
        NODE_ENV: production
      depends_on:
        postgres:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
      ports:
        - "3001:3001"
      restart: unless-stopped
      networks: [nebula-network]


volumes:
  pgdata:
    driver: local
  pgdata_notifications:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  nebula-network:
    driver: bridge
    name: nebula-network